### ISSUE TITLE
Crash on Push / Pull

### ISSUE THREAD

**Issue by tpayne84** [msysgit/git#200]
Issue Description:
When pushing and pulling for the last several weeks, git crashes (no matter the client... gui tools, command line, github app, etc)

I am able to select a debugger, then choose not to break  on the error and instead pass the error back to git and it will continue to progress in the task (sometimes not, it often fails with a  fatal object <hash> not found).  But when it does progress it will finish out its function.  This happens > 80% of the time.

SYSTEM INFO:
instance of Win32_Processor
{
	Family = 198;
};

instance of Win32_OperatingSystem
{
	BuildNumber = "9200";
	OSLanguage = 1033;
	ProductType = 1;
	ServicePackMajorVersion = 0;
	ServicePackMinorVersion = 0;
	SuiteMask = 272;
	Version = "6.2.9200";
};

instance of Win32_ComputerSystem
{
	Domain = REDACTED;
	Manufacturer = "Dell Inc.";
	Model = "Latitude E6430";
	Name = REDACTED;
	PartOfDomain = TRUE;
	UserName = REDACTED;
};

TRACE INFO:
http://pastebin.com/mxwyKCNh

**Comment by nadiarebiai** [comment]
Hi,

Is there any solution for this problem ? I have the same issue on my Windows 7 with both 1.8.4 and last version (1.9.5) I already tried reinstalling many times. It doesn't change anything and I am unable to find any helpful actions on stackoverflow.

When trying $ git clone https://github.com/msysgit/git.git , I have the following error: 
"The Instruction at 0x... referenced memory at 0x... The memory could not be read"
Same when execution $ GIT_TRACE=1 git clone https://github.com/msysgit/git.git

When trying to pull something from an ssh repository, I have this error:
Application was unable to start correctly (0xc0000142)

When trying to push anything even on a local repository, I have this error:
Application was unable to start correctly (0xc0000142)
+
Counting Object: 16, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (11/11), done.
Writing objects: 100% (16/16), 1.70 KiB | 0 bytes/s, done.
Total 16 (delta 0), reused 0 (delta 0)
error: unpack failed: unpack-objects abnormal exit
To c:/Users/[username]/test.git
 ! [remote rejected] master -> master (unpacker error)
error: failed to push some refs to 'c:/Users/[username]/test.git'

I don't have any disk space problems and I'm running the Git Bash as Administrator if it changes anything. But using PhpStorm or windows cmd, same error anyway. git status/git add and git commit seem to work fine but there's no way to make git pull/push/clone work.

Is there any clue for this problem ? It's impossible to work like this and I'll be happy to supply any details you need to help resolve this issue.

Thank you,

**Comment by dscho** [comment]
Could you test whether [Git for Windows 2.x' release candidate](https://git-for-windows.github.io/) fixes the problem?

**Comment by nadiarebiai** [comment]
Hi,

I've re-installed 1.9.5 on a different folder, on a different drive (E:\ not C:\), deleted the gitconfig file on my personal folder, migrated all my git projects to that drive and it seems to work again... 

So it seems to be some kind of permissions problem but I've already tested git commands on a project created on the E:\ drive when git was installed on C:\Program Files (x86)\Git and it wouldn't work the same. I had all administration powers on windows, folders had every permission possible on Windows and even now with the working install git bash is still using the same root folder as before (my personal folder C:\Users\[username]) so I'm not sure what was the problem.

If I have same problem again, I will try the release candidate but since this version finally works, I think I'll stick to it for the moment as I've already lost too much time trying to fix it. However, if you need further details, I'll be happy to help.

Thanks

**Comment by dscho** [comment]
My guess is that it is that infamous [DLL address range problem](https://github.com/git-for-windows/git/wiki/32-bit-issues).

In any case, since nobody seems to be interested in testing whether Git for Windows 2.x fixes the issue, I am closing this ticket, assuming that it does fix it (because I am not given any other choice).

**Comment by crutchcorn** [comment]
Having this issue on git version 2.5.0.windows.1

**Comment by theroller** [comment]
also having this issue with git version 2.11.0.windows.1 on Win7

**Comment by VisualBean** [comment]
I am having this issue on 2.11.0.windows.3 on win7

**Comment by dscho** [comment]
> 2.11.0.windows.3

You are 1) a couple of versions behind, and 2) on the wrong bug tracker ([here](https://github.com/git-for-windows/git/issues) is the bug tracker for Git for Windows 2.x).
