### ISSUE TITLE
Git 1.9.0 and Perl 5.14.1

### ISSUE THREAD

**Issue by RaymondBorbon** [msysgit/git#235]
I am very new to Git and I see my package came with Perl version 5.8. In my environment I have Perl version 5.14.1.

Is there a central location, script, configuration, setting I can alter in order to inform GIT that I have Perl 5.14.1 at a different path than what came with my GIT? I don't want to use Perl 5.8 and intend to use my existing binaries, scripts, modules. 

Related to this question... Would anyone be able to comment on whether or not something would go horribly wrong by making such a change? I couldn't tell for certain exactly what part of GIT was relying on the Perl binaries, modules, scripts, etc.

**Comment by j-ulrich** [comment]
I would be interessted in the answer to the question "what part of GIT was relying on the Perl binaries, modules, scripts, etc."
Because it is easy to make an external Perl work in the Git Bash (at least it works with ActiveState Perl). I just made sure that the external Perl's `site/bin` and `bin` directories are on the `PATH` and then copied the external `perl.exe` into Git's `bin` directory (overriding the existing `perl.exe`).
![Perl 5.16.3 in Git Bash](http://i.imgur.com/FOmPkn1.png)

So the question is which parts/commands of Git won't work this way?

**Comment by sschuberth** [comment]
AFAIK Git itself does not have any restrictions / requirements as to which Perl distribution to use (as long as it reasonably recent). So I believe Git should just work fine with ActiveState Perl. It's more a philosophical issue why we do not endorse the use of not-compiled-from-source Perl distributions.

**Comment by dscho** [comment]
> it is easy to make an external Perl work in the Git Bash (at least it works with ActiveState Perl).

Not by my definition, which is: "It only works if it passes the test suite"

**Comment by dscho** [comment]
> AFAIK Git itself does not have any restrictions / requirements as to which Perl distribution to use

Not the Perl distribution, no, but which Perl modules are required. Think of `git svn` and you'll see the problem right there.

**Comment by j-ulrich** [comment]
Ok. So the ["Git" package](https://github.com/git/git/blob/master/perl/Git.pm) (which is required by some of the git commands like [git-add--interactive](https://github.com/git/git/blob/master/git-add--interactive.perl)) exists on CPAN and can therefore be installed in the external Perl.
The only remaining problem seems to be the Git::SVN::* and Git::I18N packages which exist only in the [Git repo](https://github.com/git/git/tree/master/perl/Git) but not on CPAN.

So it sounds like everything except `git svn` should work (I didn't test it, though)
This is an acceptable drawback for me, since I don't need `git svn`.

And for the basic problem: if the packages missing on CPAN could be published, that would probably make updating/replacing Perl in the Git Bash easier:
- just install another Perl distro
- install Error (required by Git), Git, Git::SVN and Git::I18N
- replace `perl.exe`
- adapt `PATH`

However, I don't know how much work it would take to publish those packages on CPAN (need to port stuff?!).

**Comment by ashumeow** [comment]
```pl
using 5.010;
```
This command doesn't work with perl <code>v.5.8.8</code>... It only works in perl versions that are above <code>5.10</code> onwards. :(

**Comment by ashumeow** [comment]
And i would highly appreciate if this issue (https://github.com/msysgit/git/issues/235#issuecomment-117219802) is fixed into the next release of msysgit. =)

**Comment by Dirk1966** [comment]
As already said, installing a new perl in msysgit is damned difficult.  I would not do it, because "git for Windows 2" will provide you with perl 5.20 onwards.

Mixing the environments perl (for DOS/Windows), and msysgit will not work too, because of each component tries to do some workarounds for the different line endings from DOS/Windows to Unix - perl for DOS expects DOS endings - while msysgit's perl as well as msysgit expects Unix endings.
I can only discourage people of mixing for instance Strawberry perl with msysgit.

This can result very, very strange behaviour when connecting to git servers, I already saw strange effects when helping people with such a double/mixed FrankenStein setup.

If you really need the package, you should try to downgrade the perl package, that should be easier.
