### ISSUE TITLE
git-cheetah and GUI bugs when there's special characters

### ISSUE THREAD

**Issue by fffonion** [msysgit/git#265]
These two bug reproduces when path contains a "・" (without quotes)

Normally git-cheetah would add three items(Git Init Here, Git Bash, Git GUI) to explorer right-click context menu when current is directory is not a git repository.
But if path contains a "・", git-cheetah gives me 6 menu items as if this is a git repository.

And if I rename an existing git repository to some name containing "・", all features excepts git bash fails to launch.

I'm using version 1.9.4-preview20140929 on win8.1 x64, reproduce on win7 x64

**Comment by dscho** [comment]
@fffonion do you have time to work on resolving this issue?

**Comment by fffonion** [comment]
I'm now in a travel. Will work on this as soon as I'm back :)

**Comment by dscho** [comment]
@fffonion okay. Please note that building Git Cheetah from source is now as easy as [installing the Git for Windows SDK](http://git-for-windows.github.io/#download-sdk), then cloning https://github.com/msysgit/Git-Cheetah/ and running `make` in the checkout.

I would also like to ask you to open a Pull Request (even when you get stuck and the topic branch is not yet ready to merge) in the Git Cheetah project (because I am closing this ticket here: msysGit was retired in favor of the new Git for Windows 2.x).
