### ISSUE TITLE
Converting svn to git error

### ISSUE THREAD

**Issue by cicadanator** [msysgit/git#309]
couldn't truncate file at /usr/lib/perl5/site_perl/Git.pm line 1322.

I keep getting this error when I run the git svn clone command. I think this used to work in older versions from what I have found however it doesn't seem to work now.

**Comment by dscho** [comment]
@cicadanator it would be really good if you could investigate a little further. In https://github.com/git-for-windows/git/issues/128, we already figured out a work-around that *should* paper over the issue, but I still have no idea why it does not work when we try with delays 0 and 1 before trying with delay 5 (which issue convinces me that @vdbg's patch cannot work reliably). I would really appreciate it if you could spend some time on this, as I cannot reproduce the issue here and therefore have no chance to do anything about the bug without substantial help from you or @vdbg.

Let's move this discussion to https://github.com/git-for-windows/git/issues/128, BTW.
