### ISSUE TITLE
Tools request

### ISSUE THREAD

**Issue by tetra-archos** [msysgit/git#327]
I would like to request the dd and mkfs tools be added to give more control of drives.

**Comment by dscho** [comment]
@tetra-archos I am sorry if you got the impression that this is a wish tracker... :laughing: 

First of all, the *Git for Windows* project is a project by – and for! – contributors. So if you want something, make it happen. Everybody involved in this project got their lazy bum up from the comfy chair at some point, and so can you.

Second, I fear that you mistake the *Git for Windows* project to be something that it is not: a port to Windows of all the tools you are used from Linux. In particular, it should be noted that the `dd` and `mkfs` tools will *never* give you more control of drives on Windows because drives are simply not available as part of the file system. There is no `/dev/this` and `/dev/that` on Windows.

Having said that, if you declare this to be your project, and that you will work on this, I am willing to keep this ticket open.

**Comment by tetra-archos** [comment]
And the dickish way you said that has mad sure that I will never use, support, or contribute to this project. You assume that because I haven't implemented this to your code base then I am lazy, when I merely lack the knowledge on how to do so. To your second point the in particular part I don't think you understand what dd and mkfs do because they can work on windows drives. Having said that I hope you being an asshole about things doesn't scare off more people to what seemed like a nifty project.

**Comment by dscho** [comment]
@tetra-archos thanks for your comments!
