### ISSUE TITLE
Why old version of grep?

### ISSUE THREAD

**Issue by cool-RR** [msysgit/git#347]
I see that the version of grep I have that I got from msysgit is 2.4.2, which is pretty old. It doesn't have the `-o` flag. How can I get an updated version? Why doesn't Msysgit have the most recent version of such tools?

**Comment by linquize** [comment]
Please use git for windows 2.x (https://github.com/git-for-windows/git/releases) if you need newer versions of `grep`, `bash` as well as other unix utilities.

**Comment by cool-RR** [comment]
Awesome, thank you!

**Comment by dscho** [comment]
> Why doesn't Msysgit have the most recent version of such tools?

Heh... The common answer in Open Source projects is: because no contributor (such as yourself) improved the situation...

In any case, your problem is solved, it seems, even if the Git for Windows 2.x developers' preview is technically intended for an audience of developers who want to help with the development of Git for Windows itself.
