### ISSUE TITLE
Removing remotes does not delete the folder in .git/refs/remotes

### ISSUE THREAD

**Issue by mikeparker** [msysgit/git#355]
This may not cause any issues, but I assume this should probably be gone on deletion?

I'm using the latest version (1.9.5)

**Comment by linquize** [comment]
Linux version of git also does not delete empty refs folder

**Comment by NysItsFrgDougM** [comment]
This *does* cause an issue, when you latter add a new remote with different capitalization.  It's a filesystem-specific bug, too, since it only affects if the capitalization is different.

**Comment by linquize** [comment]
Yes, exactly. You also need to look at `.git/packed-refs` and see if casing differs from loose ref directories `.git/refs/remotes/`.

**Comment by dscho** [comment]
Wait a moment. How does an empty `.git/refs/remotes/` directory (all lower-case) affect remotes whose names differ in case from previous ones'? Unless you say that empty *subdirectories* of `.git/refs/remotes/` are left behind, I don't get it.

**Comment by NysItsFrgDougM** [comment]
Please re-open.


Yes, it's a subfolder of .git/refs/remotes/


On Windows NTFS:


1: Add a "Doug" remote and do a fetch.  the .git/refs/remotes/Doug folder is created.

2: Remote the "Doug" remote.  The ".git/refs/remotes/Doug" folder remains.

3: Add a new "doug" remote; a ".git/refs/remotes/doug" folder is not created, since NTFS treats it as ".git/refs/remotes/Doug"

4: User is now unable to fetch / manage their remotes.

**Comment by dscho** [comment]
You sure took your time to respond.

Now that the symptom is established, it is also clear that this is a case-insensitive file system issue, i.e. a bug in upstream Git. Please report it on the Git mailing list: git@vger.kernel.org
